/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Bottle {
  content?: string;
  created_at: Date;
  geo: {
    lat: number;
    lng: number;
  };
  kind?: 'text';
  uid: string;
}

export interface BottleCreateDOI {
  content?: string;
  geo: {
    lat: number;
    lng: number;
  };
  kind?: 'text';
}
