/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Mission {
  _class_id?: number;
  /**
   * Unified typesense, firestore, and client geoposition data type, [lat, lng]
   */
  center: any[];
  /**
   * a firebase timestamp (If getting data from firestore) or js date (if creating data to store to firestore)
   */
  createdAt: {
    _nanoseconds?: number;
    _seconds?: number;
  } | {
    nanoseconds?: number;
    seconds?: number;
  } | Date;
  description: string;
  enable: boolean;
  /**
   * a firebase timestamp (If getting data from firestore) or js date (if creating data to store to firestore)
   */
  endAt?: {
    _nanoseconds?: number;
    _seconds?: number;
  } | {
    nanoseconds?: number;
    seconds?: number;
  } | Date;
  geofence?: any[][];
  kind: 'geofence' | 'geofence+picture' | 'geofence+posted' | 'geofence+posted+dated';
  reward: string[];
  /**
   * a firebase timestamp (If getting data from firestore) or js date (if creating data to store to firestore)
   */
  startAt?: {
    _nanoseconds?: number;
    _seconds?: number;
  } | {
    nanoseconds?: number;
    seconds?: number;
  } | Date;
}

export interface MissionCreate {
  _class_id?: number;
  /**
   * Unified typesense, firestore, and client geoposition data type, [lat, lng]
   */
  center: any[];
  /**
   * a firebase timestamp (If getting data from firestore) or js date (if creating data to store to firestore)
   */
  createdAt: {
    _nanoseconds?: number;
    _seconds?: number;
  } | {
    nanoseconds?: number;
    seconds?: number;
  } | Date;
  description: string;
  enable: boolean;
  /**
   * a firebase timestamp (If getting data from firestore) or js date (if creating data to store to firestore)
   */
  endAt?: {
    _nanoseconds?: number;
    _seconds?: number;
  } | {
    nanoseconds?: number;
    seconds?: number;
  } | Date;
  geofence?: any[][];
  id: string;
  kind: 'geofence' | 'geofence+picture' | 'geofence+posted' | 'geofence+posted+dated';
  reward: string[];
  /**
   * a firebase timestamp (If getting data from firestore) or js date (if creating data to store to firestore)
   */
  startAt?: {
    _nanoseconds?: number;
    _seconds?: number;
  } | {
    nanoseconds?: number;
    seconds?: number;
  } | Date;
}
