/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface IndexByGeocordReqDTO {
  /**
   * Unified typesense, firestore, and client geoposition data type, [lat, lng]
   */
  geo?: any[]
  /**
   * show post as recent as x minutes, default to 24 hours
   */
  minutes?: number
}

export interface SearchReqDTO {
  page?: number
  perPage?: number
  q: string | '' | null
  searchKind: 'all' | 'users' | 'bottles'
}
