/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { IMedia } from '.';

export interface UserMetaAggegator {
  commentCount: number;
  likeCount: number;
  postCount: number;
  recvCommentCount: number;
  recvLikeCount: number;
}

export interface UserProfile {
  /**
   * Unified media storage type, with thumbnail support (Not only images)
   */
  avatar?: IMedia;
  description?: string;
  displayName?: string;
  follows?: any[];
  recvFollows?: any[];
  registeredAt: Date;
  username: string;
}

export interface UserProfileSummaryGet {
  displayName?: string;
  username: string;
}

export interface UserUpdateProfile {
  description?: string;
  displayName?: string;
  facebook?: string;
  instagram?: string;
  twitter?: string;
}
