/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface UserMetaAggegator {
  commentCount: number;
  likeCount: number;
  postCount: number;
  recvCommentCount: number;
  recvLikeCount: number;
}

export interface UserMetaSchema {
  aggregator?: UserMetaAggegator;
  socials?: UserMetaSocials;
}

export interface UserMetaSocials {
  facebook?: string;
  instagram?: string;
  twitter?: string;
}
