/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface UserMetaAggegator {
  commentCount: number
  likeCount: number
  postCount: number
  recvCommentCount: number
  recvLikeCount: number
}

export interface UserProfile {
  description?: string
  displayName?: string
  follows?: any[]
  recvFollows?: any[]
  registeredAt: Date
  username: string
}

export interface UserProfileGet {
  displayName?: string
  username: string
}

export interface UserUpdateProfile {
  description?: string
  displayName?: string
  facebook?: string
  instagram?: string
  twitter?: string
}
