/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface UserProfile {
  description?: string
  displayName?: string
  registeredAt: Date
  username?: string
}
